POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "Curso de Python",
  "description": "Um bom Curso!"
}

###

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/31b84e0f-1f3e-46fd-b551-3549d7e436da

###

PUT http://localhost:3000/courses/34asd
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

DELETE http://localhost:3000/courses/9a1d6afd-b768-47f3-b883-d2ac5252358b